export const watch = [
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: "165 000 руб." },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: "165 000 руб." },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: "165 000 руб." },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: "165 000 руб." },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: "165 000 руб." },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
  { name: "Louis XVI ATHOS", img: "/img/watch.png", price: '165 000 руб.' },
];
